let staticCats = [
  {
    id: 59,
    name: "Tess",
    age: "Young",
    size: "M",
    sex: "F",
    breed: "Domestic Short Hair",
    contact_phone: null,
    contact_email: "rescue.grassroots@gmail.com",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/40753391/1/?bust=1516753335&width=300&-pn.jpg",
    user_id: 1,
    description: "Tess was found as a baby all alone in the big scary city. She was terrified of people and new things. But this sweet girl has come so far in just a short time! And she continues to blossom. Now she's playful and curious, purring immediately when she gets scratched behind the ear. She follows her foster mom around, and runs ahead of her to leap atop the bed when it's time to go to sleep. She has an adorable little trill that she makes when she wants attention. And she loves her foster cat siblings--She is frequently found romping about the apartment with them or bathing the other kittens. She even leads the way to cozy up to strangers! She would be the perfect cat for a calmer home, with another cat and a pet parent who loves a cat who is full of slow blinks, head butts, and simply bursting with love. If you are interested in meeting Tess, please fill out the application below: http://www.grassrootsanimalrescue.org/#!application/c2v2 ",
    created_at: "2018-04-16T03:50:20.889Z",
    updated_at: "2018-04-16T03:50:20.889Z"
  },
  {
    id: 60,
    name: "Marco",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Domestic Short Hair",
    contact_phone: null,
    contact_email: "rescue.grassroots@gmail.com",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41351255/1/?bust=1523128343&width=300&-pn.jpg",
    user_id: 1,
    description: "Eager to play and willing to snuggle, Marco is named for his adventurous spirit. He's a wonderful cat, who was found in a Chicago alley on a cold fall day attempting to drink foul water. He easily accepted being in a car and was a gentleman throughout all veterinarian procedures. He is fully vaccinated, neutered, and in robust health. A talkative fellow he enjoys playing with humans and dogs and would likely do well with other cats. His litter box behavior is excellent and he loves exploring the outdoors on a harness. Fill out an application to meet Marco today!",
    created_at: "2018-04-16T03:50:20.905Z",
    updated_at: "2018-04-16T03:50:20.905Z"
  },
  {
    id: 61,
    name: "Aqua",
    age: "Young",
    size: "S",
    sex: "F",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41339053/1/?bust=1522986451&width=300&-pn.jpg",
    user_id: 1,
    description: "I am the purrrfect pet! I love to play and explore. having someone pet me makes me sooo happy. I am young and great with pets and kids. -I just want to have a home to call my own. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.918Z",
    updated_at: "2018-04-16T03:50:20.918Z"
  },
  {
    id: 62,
    name: "Rocket",
    age: "Senior",
    size: "L",
    sex: "F",
    breed: "Tortoiseshell",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41339052/1/?bust=1522986451&width=300&-pn.jpg",
    user_id: 1,
    description: "My owner has Alzheimer's and couldn't care for me or my 4 siblings. I miss having a human to love and I miss my own space. I am quiet and loving and am just looking for a wonderful person to call my own again. Older cats deserve a place to call their own! Won't you bring me home? This To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.937Z",
    updated_at: "2018-04-16T03:50:20.937Z"
  },
  {
    id: 63,
    name: "Bruce",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41335423/1/?bust=1522986452&width=300&-pn.jpg",
    user_id: 1,
    description: "Are you lonely? Then you are looking for me! I LOVE people and I just love to be around them. I love to talk and tell you about my day. I can be an only cat or I can hang with other animal friends too. I am very sweet and would play and cuddle anyone who needs it! To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.952Z",
    updated_at: "2018-04-16T03:50:20.952Z"
  },
  {
    id: 64,
    name: "FLOSSY",
    age: "Adult",
    size: "M",
    sex: "F",
    breed: "Tabby",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41339050/1/?bust=1522986449&width=300&-pn.jpg",
    user_id: 1,
    description: "MY owner died and I was left alone with my 3 brother and sisters. They all got adopted but because I am shy, everyone overlooks me. I have become more trusting and am very friendly if you take the time to get to know me. I love to sit on laps and purr the day away. Won't someone just give me a chance??? To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.966Z",
    updated_at: "2018-04-16T03:50:20.966Z"
  },
  {
    id: 65,
    name: "Simba",
    age: "Senior",
    size: "L",
    sex: "M",
    breed: "Domestic Long Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41339049/1/?bust=1522986450&width=300&-pn.jpg",
    user_id: 1,
    description: "I am big and handsome just like a Lion -but I am just an old softy. I love to lay around and cuddle and watch the world go by. I am looking for a friendly place to spend my days. In return I will repay you love. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.979Z",
    updated_at: "2018-04-16T03:50:20.979Z"
  },
  {
    id: 66,
    name: "Got Milk",
    age: "Adult",
    size: "M",
    sex: "F",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500778/1/?bust=1497915390&width=300&-pn.jpg",
    user_id: 1,
    description: "Please contact Marijon Binder (marijonbinder@yahoo.com) for more information about this pet. Hi, my name is Got Milk. You may be wondering how I got such a unique name. Well, I am a very unique cat. I have a little white 'milk' mustache on my upper mouth. It's very different and I love it. I'm a very cool cat. I'm very laid-back, but I like to play...on my time, of course. Are you looking for a laid-back but playful cat who's as good looking and interesting as me? To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:20.992Z",
    updated_at: "2018-04-16T03:50:20.992Z"
  },
  {
    id: 67,
    name: "Logan",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Tabby",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500781/1/?bust=1497915407&width=300&-pn.jpg",
    user_id: 1,
    description: "Please contact Marijon Binder (marijonbinder@yahoo.com) for more information about this pet.My name is Logan. Iâm a shy orange tabby who loves to lounge around and play hide and seek. Iâm a little nervous when I first meet someone, but once you get to know me Iâve very loveable. You should stop by and meet me sometime. Iâm sure you wonât be able to help but fall in love with me. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.023Z",
    updated_at: "2018-04-16T03:50:21.023Z"
  },
  {
    id: 68,
    name: "Poppy",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Domestic Medium Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500782/1/?bust=1517438191&width=300&-pn.jpg",
    user_id: 1,
    description: "Please contact Marijon Binder (marijonbinder@yahoo.com) for more information about this pet. Hi! I'm Poppy. My brothers and sisters and I moved to Cats-Are-Purrsons-Too a few years ago, and all of them were adopted pretty quickly. But I'm still here and looking for my forever home. I'm a sweet, boy who likes to take cat naps and play, but I'm a little shy until I first get to know a person. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.040Z",
    updated_at: "2018-04-16T03:50:21.040Z"
  },
  {
    id: 69,
    name: "Paddy McGee",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: null,
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500783/1/?bust=1497915408&width=300&-pn.jpg",
    user_id: 1,
    description: "I'm Paddy McGee, but you can call me Paddy. They named me that because I came to Touched by an Animal right around St. Patrick's Day. I'm a shy guy with a lot of love to give. If you give me a chance, I'll be your best friend, but you're going to have to make the first move, because I don't think I'd know what to say. I like to sit high up in cat trees and watch all the other cats and people walk by, but I think I'd like it more to sit on a nice soft quiet sofa with you! To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.047Z",
    updated_at: "2018-04-16T03:50:21.047Z"
  },
  {
    id: 70,
    name: "Paisley",
    age: "Adult",
    size: "M",
    sex: "F",
    breed: "Domestic Medium Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500784/1/?bust=1501349654&width=300&-pn.jpg",
    user_id: 1,
    description: "My name is Paisley, and I think it's high time you called the people at Touched by an animal to take me home with you! I'm adorable, and fun-loving and playful and...did I mention adorable? I mean really, who could resist this face? I'm everything anyone could ever want in a cat! I came here with my two brothers and two sisters, and it's been a blast, but I've been waiting for you to call about me. I've been waiting for you to come pick me up. Pick up the phone already! To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.069Z",
    updated_at: "2018-04-16T03:50:21.069Z"
  },
  {
    id: 71,
    name: "Argyle",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500785/1/?bust=1522958300&width=300&-pn.jpg",
    user_id: 1,
    description: "Hi! I'm Argyle. I like to meow and coo and purr up a storm. Do you like to talk? Because I'd like to have a chat with you sometime soon! I came here with my three sisters and one brother and, while I really like the people and the other cats, I think I need a purrson of my own to cuddle and snuggle and play with me. I love attention and won't hesitate to let you know in my own native language. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.076Z",
    updated_at: "2018-04-16T03:50:21.076Z"
  },
  {
    id: 72,
    name: "Stripe",
    age: "Adult",
    size: "M",
    sex: "F",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500787/1/?bust=1497915398&width=300&-pn.jpg",
    user_id: 1,
    description: "I'm Stripe....I'm a little shy sometimes...like, when I meet new people...or when I see people I've met before but can't remember their name...or when I see people whose name I remember but it's been a while... I'd like to get to know you better. Just please be patient with me. I'm still growing up and learning that everything are okay. My brothers and sisters all seem to have gotten the hang of it, but I'm a little more cautious than they are...better safe than sorry, because I heard what curiousity did to that cat! What's your house like? Is it safe? I'm sure you say it is, but I might have to come over and make sure for myself...and if you're right, I might just make myself comfortable and call it my home too! I bet you'd make a pretty good roommate. I know I would. I'm quiet as a mouse (until I get to know you a little better, then my favorite thing is snuggling!) To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.085Z",
    updated_at: "2018-04-16T03:50:21.085Z"
  },
  {
    id: 73,
    name: "Buster Brown",
    age: "Adult",
    size: "M",
    sex: "M",
    breed: "Tabby",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/41339051/1/?bust=1522986449&width=300&-pn.jpg",
    user_id: 1,
    description: "My name is Buster Brown but everyone calls me Mouse! They say my face looks just like a mouse. I am very curious and I like to get into everything,Of course my curiosity allows me to find wonderful hiding places to curl up and nap. I do love a nice lap to sleep on as well and would make a great friend to someone looking for a cat with an equal mix of love and playfulness! To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336, or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.100Z",
    updated_at: "2018-04-16T03:50:21.100Z"
  },
  {
    id: 74,
    name: "Penguin",
    age: "Adult",
    size: "M",
    sex: "F",
    breed: "Domestic Short Hair",
    contact_phone: "773-728-6336",
    contact_email: "adopt@touchedbyananimal.org",
    contact_city: "Chicago",
    photo: "http://photos.petfinder.com/photos/pets/38500780/1/?bust=1497915413&width=300&-pn.jpg",
    user_id: 1,
    description: "Hi my name is Penguin. I am a little shy at first, but very sweet once you get to know me. I LOVE to play and be petted. I just know I'd be a great new addition to your family. Just meet me and you'll fall in love with me! I just know you're the purrson for me. To offer me a loving home, please call the nice people at Touched By An Animal/Cats-Are-Purrsons-Too at (773)728-6336 or e-mail them at TBA@touchedbyananimal.org. 4/5/18 3:34 PM",
    created_at: "2018-04-16T03:50:21.276Z",
    updated_at: "2018-04-16T03:50:21.276Z"
  }
]

module.exports = {
  staticCats
}